# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f6b98419ba943df757275b488831819390c6e3e6dd3267585e5dca083accbf6e5711266f27390d6911d64e8a6603d16e01525a407a9350b9624a66bdc689d295

test:
  secret_key_base: 1c3bb7ff6d0c36c167de704b943a0ed654903aae3346fcc072df2c0c0b39c53738f82091b79089d2d987673ad26169072feb9e135fab2ef18b5c8d970321b3a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
